/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package citbyui.cit260.wordscramble.frames;

import citbyui.cit260.wordscramble.controls.WordMenuControl;
import static citbyui.cit260.wordscramble.controls.WordMenuControl.wordLength;
import javax.swing.JLabel;
import wordscramble.GuessCheck;
import wordscramble.PlayGame;
import wordscramble.Timer;
import wordscramble.WordScramble;

/**
 *
 * @author Aubrey
 */
public class PlayGameFrame extends javax.swing.JFrame {

    public static String guess;
    public static String checkGuess;
    public static String gameOverMessage;
    public static long startTime;
    public static float totalTime;
    private int guessResult;
    GuessCheck myGuessCheck = new GuessCheck();
    PlayGame myPlayGame = new PlayGame();
    Timer myTimer = new Timer();



    WordMenuControl userGuess = new WordMenuControl();
    WordMenuControl maxAttempts = new WordMenuControl();

    public JLabel getjResultMessage() {
        return jResultMessage;
    }

    /**
     * Creates new form PlayGameFrame
     */
    public PlayGameFrame() {
        initComponents();
        startTime = myTimer.start();
    }
    private static void PlayGameDispose(){
        // .dispose();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpBody = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jpTitle = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jmyGuess = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jResultMessage = new javax.swing.JLabel();
        jCheckGuess = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(222, 222));
        setLocationByPlatform(true);

        jpBody.setBackground(new java.awt.Color(255, 255, 208));
        jpBody.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 255, 153), 3));
        jpBody.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        jLabel1.setToolTipText("");

        jpTitle.setBackground(new java.awt.Color(255, 255, 208));
        jpTitle.setToolTipText("");

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 36)); // NOI18N
        jLabel2.setText("WordScramble");

        javax.swing.GroupLayout jpTitleLayout = new javax.swing.GroupLayout(jpTitle);
        jpTitle.setLayout(jpTitleLayout);
        jpTitleLayout.setHorizontalGroup(
            jpTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpTitleLayout.createSequentialGroup()
                .addContainerGap(143, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(31, 31, 31))
        );
        jpTitleLayout.setVerticalGroup(
            jpTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpTitleLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jmyGuess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmyGuessActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel3.setText("This is your scrambled word: " +myPlayGame.getScrambledWord());

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel4.setText("Enter your Guess here:");

        jResultMessage.setFont(new java.awt.Font("Lucida Grande", 3, 14)); // NOI18N
        jResultMessage.setForeground(new java.awt.Color(204, 102, 0));

        jCheckGuess.setText("Guess");
        jCheckGuess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckGuessActionPerformed(evt);
            }
        });

        jLabel5.setText("You have 3 tries to guess the right word. Good luck!");

        javax.swing.GroupLayout jpBodyLayout = new javax.swing.GroupLayout(jpBody);
        jpBody.setLayout(jpBodyLayout);
        jpBodyLayout.setHorizontalGroup(
            jpBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpBodyLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 466, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(419, 419, 419))
            .addGroup(jpBodyLayout.createSequentialGroup()
                .addGroup(jpBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpBodyLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jpTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(486, 486, 486)
                        .addComponent(jLabel1))
                    .addGroup(jpBodyLayout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpBodyLayout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addGroup(jpBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jResultMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jpBodyLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jmyGuess, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckGuess)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpBodyLayout.setVerticalGroup(
            jpBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpBodyLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jpBodyLayout.createSequentialGroup()
                .addComponent(jpTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addGap(30, 30, 30)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jResultMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jpBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jmyGuess, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckGuess))
                .addGap(66, 66, 66))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpBody, javax.swing.GroupLayout.PREFERRED_SIZE, 553, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jpBody, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmyGuessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmyGuessActionPerformed
        Object CheckGuess = evt.getSource();

        guess = this.jmyGuess.getText();
      //  java.awt.EventQueue.invokeLater(new Runnable() {
        //    public void run() {
        guessResult = myGuessCheck.checker(myPlayGame.getOrigWord(), myPlayGame.getScrambledWord(), wordLength, guess);
       //jResultMessage.setText(Integer.toString(myGuessCheck.checker(myPlayGame.getOrigWord(), myPlayGame.getScrambledWord(), 3, guess)));
        //myTimer.stop();
        if (guessResult == 0) {
            totalTime = myTimer.getElapsedTimeSecs(PlayGameFrame.startTime);
            jResultMessage.setText("Good Job!");
            gameOverMessage = jResultMessage.getText();
            myPlayGame.endGame(1, wordLength);
            new PlayAgainFrame().setVisible(true);
           // PlayGameFrame.PlayGameDispose();
            //PlayGameFrame.PlayGameDispose();
            
        this.dispose();
        }else if(guessResult==3){
            totalTime = myTimer.getElapsedTimeSecs(PlayGameFrame.startTime);
            jResultMessage.setText("Sorry, game over.");
            gameOverMessage = jResultMessage.getText();
            myPlayGame.endGame(0, wordLength);
            new PlayAgainFrame().setVisible(true);
        this.dispose();
        }else{
            jResultMessage.setText("Incorrect, please try again.");
            gameOverMessage = jResultMessage.getText();
            this.jmyGuess.setText("");
            
        }
       //     } 
        //});
//this.dispose();
        
    }//GEN-LAST:event_jmyGuessActionPerformed

    private void jCheckGuessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckGuessActionPerformed
        Object CheckGuess = evt.getSource();

        guess = this.jmyGuess.getText();
       // java.awt.EventQueue.invokeLater(new Runnable() {
           // public void run() {
        guessResult = myGuessCheck.checker(myPlayGame.getOrigWord(), myPlayGame.getScrambledWord(), wordLength, guess);
       //jResultMessage.setText(Integer.toString(myGuessCheck.checker(myPlayGame.getOrigWord(), myPlayGame.getScrambledWord(), 3, guess)));
        //myTimer.stop();
        if (guessResult == 0) {
            totalTime = myTimer.getElapsedTimeSecs(PlayGameFrame.startTime);
            jResultMessage.setText("Good Job!");
            gameOverMessage = jResultMessage.getText();
            myPlayGame.endGame(1, wordLength);
            new PlayAgainFrame().setVisible(true);
            //PlayGameFrame.PlayGameDispose();
            
        this.dispose();
        }else if(guessResult==3){
            totalTime = myTimer.getElapsedTimeSecs(PlayGameFrame.startTime);
            jResultMessage.setText("Sorry, game over.");
            gameOverMessage = jResultMessage.getText();
            myPlayGame.endGame(0, wordLength);
            new PlayAgainFrame().setVisible(true);
        this.dispose();
        }else{
            jResultMessage.setText("Incorrect, please try again.");
            gameOverMessage = jResultMessage.getText();
            this.jmyGuess.setText("");
            
        }
          //  } 
       // });
//this.dispose();
        
    }//GEN-LAST:event_jCheckGuessActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jCheckGuess;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jResultMessage;
    private javax.swing.JTextField jmyGuess;
    private javax.swing.JPanel jpBody;
    private javax.swing.JPanel jpTitle;
    // End of variables declaration//GEN-END:variables
}
